### ISSUE TITLE
Help.

### ISSUE THREAD

**Issue by EbriuuidTas** [liketechnik/Liketechnik-s-Tinker-Tweaks#1]
Its the mod or my modpack?. I just installed it togheter with Tinkers' Construct and it doesn't show the xp on the tools and idk if im leveling them.

I love the idea but i dont know if is working for me.  I dont understand.

Sorry.

**Comment by EbriuuidTas** [comment]
And sorry for bad english.

**Comment by liketechnik** [comment]
Did you craft the tools before you added the mod?

**Comment by EbriuuidTas** [comment]
Yes

**Comment by EbriuuidTas** [comment]
Is that the problem?

**Comment by EbriuuidTas** [comment]
nvm it was. Sorry for the inconvenience and thanks.

**Comment by liketechnik** [comment]
Yes, I'm not sure if you can just place it in a crafting table or if you have to utilise the toolstation, but one of these options should fix the tool.

Am 14. November 2018 18:36:17 MEZ schrieb EbriuuidTas <notifications@github.com>:

**Comment by liketechnik** [comment]
Glad you solved it. Much fun!
